'use client';
import { Card, CardContent } from "@/components/ui/card";
import InputBox from "./fieldbox";

interface Postedjobprops {
    description: string;
    company: string;
    type: string;
    currency: string;
    salary: string;
}

export default function JobpProfile({ data }: { data: any }) {
  if (!data) return null;

  return (
    <div className="space-y-6 p-4">
      <div className="text-center">
        <h1 className="text-xl font-semibold font-sans text-gray-800">
          {data.job_title}
        </h1>
        <p className="text-sm text-gray-600 mt-1">
          {data.job_description}
        </p>
      </div>

      <Card className="w-full shadow-md border rounded-xl">
        <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-6 p-6 text-sm text-gray-700">
          <div>
            <h2 className="font-semibold text-gray-900 mb-2">Company Info</h2>
            <p><span className="font-medium">Company:</span> {data.company_name}</p>
            <p><span className="font-medium">Location:</span> {data.location}</p>
            <p><span className="font-medium">Type:</span> {data.job_type}</p>
          </div>
          <div>
            <h2 className="font-semibold text-gray-900 mb-2">Salary & Date</h2>
            <p><span className="font-medium">Salary:</span> {data.currency} {data.salary}</p>
            <p><span className="font-medium">Posted on:</span> {new Date(data.created_at).toLocaleDateString()}</p>
          </div>
        </CardContent>
      </Card>

      {/* <div>
        <h2 className="text-lg font-semibold text-gray-800 mb-2">AI Powered Questions</h2>
        <p className="text-sm text-gray-600 italic">Relevant questions generated by AI (if any)</p>
      </div> */}

      <div>
        <h2 className="text-lg font-semibold text-gray-800 mb-2">Requirements</h2>
        <ul className="list-decimal list-inside space-y-1 text-sm text-gray-700">
          {data.requirements.map((req: string, idx: number) => (
            <li key={idx}>{req}</li>
          ))}
        </ul>
      </div>

      <div>
        <h2 className="text-lg font-semibold text-gray-800 mb-2">Responsibilities</h2>
        <ul className="list-disc list-inside space-y-1 text-sm text-gray-700">
          {data.responsibilities.map((res: string, idx: number) => (
            <li key={idx}>{res}</li>
          ))}
        </ul>
      </div>

      <div>
        <h2 className="text-lg font-semibold text-gray-800 mb-2">Skills</h2>
        <div className="flex flex-wrap gap-2">
          {data.skills.map((skill: string, idx: number) => (
            <span key={idx} className="bg-[#f7941D] text-white text-xs px-3 py-1 rounded-full">
              {skill}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}
